<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerELDkW2l\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerELDkW2l/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerELDkW2l.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerELDkW2l\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerELDkW2l\App_KernelDevDebugContainer([
    'container.build_hash' => 'ELDkW2l',
    'container.build_id' => 'de1ae1c2',
    'container.build_time' => 1640660604,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerELDkW2l');
